### ISSUE TITLE
Erro da biblioteca

### ISSUE THREAD

**Issue by ltcdata** [samuels4fe/keyboard-microcontrollers#1]
Saudações Samuel, tudo bem?
Estive na busca de uma solução como a sua para mitigar a troca das teclas para o Attiny85. Segui o procedimento mas recebi erro durante a compilação. 
 
[Arduino_error.txt](https://github.com/samuels4fe/keyboard-microcontrollers/files/9560766/Arduino_error.txt)

**Comment by samuels4fe** [comment]
Olá

Para compilar com sucesso recomendo que use arduino 1.6.7 - 1.8.19 no Windows 10
Baixe os drivers https://github.com/digistump/DigistumpArduino/releases 

Configure a placa em preferencias no Arduino  adicionando a URL https://raw.githubusercontent.com/digistump/arduino-boards-index/master/package_digistump_index.json

Selecione a placa em Ferramentas > Placas >  Digistump/Digispark (Default 16.5mhz)


É possível verificar no documento que passou que a versão que esta sendo utilizada (1.7.5) para compilar é diferente da compatível/recomendada (1.6.7) com as bibliotecas "Digispark" 

Depois é só realizar as orientações do README
