### ISSUE TITLE
A pasta lib não aparece no pc

### ISSUE THREAD

**Issue by AlekCG** [samuels4fe/keyboard-microcontrollers#2]
Eu tenho meu Digispark (Attiny85) já configurado e com códigos, como originalmente eles apenas rodam no layout em inglês eu quis trocar, mas a pasta **%appdata%..\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\DigisparkKeyboard** que o readme diz para entrar não existe em meu pc (mesmo com digispark conectado), tentei também usar o Arduino IDE mas acabou dando erro nos códigos na hora de fazer upload, eu estaria fazendo algo errado (quase certeza) ou existe um erro nos códigos?

**Comment by samuels4fe** [comment]
Olá

Para compilar com sucesso recomendo que use arduino 1.6.7 - 1.8.19 no Windows 10
Baixe os drivers https://github.com/digistump/DigistumpArduino/releases

Configure a placa em preferencias no Arduino adicionando a URL https://raw.githubusercontent.com/digistump/arduino-boards-index/master/package_digistump_index.json

Selecione a placa em Ferramentas > Placas > Digistump/Digispark (Default 16.5mhz)

Depois é só realizar as orientações do README
